# Generated by Django 6.0.3 on 2026-03-16 11:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(choices=[('DEBT', 'Debt'), ('RECEIVABLE', 'Receivable')], max_length=20)),
                ('person_name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek Som'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble')], default='UZS', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt Record',
                'verbose_name_plural': 'Debt Records',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
